default: &default
  adapter: postgresql
  encoding: unicode
  username: postgresql
  password: postgresql
  host: localhost
  port: 5432

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test

production:
  <<: *default
  database: backend